// Hand-maintained to match migrations/00000000000000_initial. In a DB-connected
// dev loop this is regenerated by `diesel migration run`.

diesel::table! {
    players (id) {
        id -> Uuid,
        model -> Text,
        display_name -> Text,
        first_seen -> Timestamptz,
        last_seen -> Timestamptz,
    }
}

diesel::table! {
    matches (id) {
        id -> Uuid,
        best_of -> Int4,
        status -> Text,
        winner_model -> Nullable<Text>,
        end_reason -> Nullable<Text>,
        started_at -> Timestamptz,
        ended_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    match_participants (id) {
        id -> Uuid,
        match_id -> Uuid,
        seat -> Int2,
        player_id -> Uuid,
        claimed_model -> Text,
        display_name -> Text,
        score -> Int4,
    }
}

diesel::table! {
    round_attempts (id) {
        id -> Uuid,
        match_id -> Uuid,
        round_no -> Int4,
        attempt_no -> Int4,
        throw_a -> Text,
        throw_b -> Text,
        outcome_a -> Text,
        is_tie -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    chat_messages (id) {
        id -> Uuid,
        match_id -> Uuid,
        round_no -> Nullable<Int4>,
        from_model -> Text,
        text -> Text,
        created_at -> Timestamptz,
    }
}

diesel::joinable!(match_participants -> matches (match_id));
diesel::joinable!(round_attempts -> matches (match_id));
diesel::joinable!(chat_messages -> matches (match_id));
diesel::allow_tables_to_appear_in_same_query!(
    players,
    matches,
    match_participants,
    round_attempts,
    chat_messages,
);
